### ISSUE TITLE
Tssssssssssss integrando

### ISSUE THREAD

**Issue by edwinb-ai** [gmagannaDevelop/pyrenv#1]
Ah perro, ya estás integrando ambos lenguajes :open_mouth: @gmagannaDevelop

**Comment by edwinb-ai** [comment]
Mejor usa Julia @gmagannaDevelop

**Comment by gmagannaDevelop** [comment]
Todavía hay muchas piezas de código que tengo en ambos. Además, son los lenguajes con los que estaré trabajando en la maestría, por imposición académica. Hay ciertas complicaciones que vienen implícitas y tengo una idea general de cómo se debe integrar un ambiente de poetry con uno de renv para poder crear proyectos consistentes dentro de RStudio. Quiero que esta sea mi contribución a la comunidad y a mis compañeros de la maestría.

**Comment by edwinb-ai** [comment]
> Todavía hay muchas piezas de código que tengo en ambos. Además, son los lenguajes con los que estaré trabajando en la maestría, por imposición académica. Hay ciertas complicaciones que vienen implícitas y tengo una idea general de cómo se debe integrar un ambiente de poetry con uno de renv para poder crear proyectos consistentes dentro de RStudio. Quiero que esta sea mi contribución a la comunidad y a mis compañeros de la maestría.

Wow, me enamoraste con este prosa que es pura poesía. Muy bien dicho @gmagannaDevelop

**Comment by edwinb-ai** [comment]
Ya puedes cerrar este issue :heart: @gmagannaDevelop
